pipeline {
    agent any
    stages {
        
        stage('Merge'){
            steps{
                sh script: """
                    set -x
                    git branch -a
                    git checkout -b develop origin/develop
                    git checkout -b main origin/main
                    git merge develop
                    pwd
                    whoami
                    cd
                    mkdir testssh001
                    cd testssh001
                """, label: "Merging code to master"
                sshagent(['aws-lab-ec2-git']) {
                    sh "git ls-remote git@github.com:kendor07/todo_list_aws.git"
                    sh "git push origin main"
                }

            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}